version: '3.8'
services:
      app : 
         image: react-image
         build:
            context: .
            dockerfile: Dockerfile
         volumes:
               - ./:/app
         ports:
           - 3001:3000
         env_file:
              ./.env
         container_name: react-container
          