version: '3.8'

services:

  app:
    image:
      backend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    container_name: backend-container
 