services:
  app:
    image: todo-frontend-image
    build:
      context:  ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend:/app
    ports:
      - 3000:3000
    container_name: todo-frontend-container
  debug-helper:
    image: busybox
  
  api:
    image: todo-backed-image
    build:
      context:  ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend:/app
    ports:
      - 3001:3000
    container_name: todo-backend-container

  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started