version: '3.8'

services:

  app:
    image:
      app_backend_image
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    environment:
        REDIS_URL: redis://redis:6379
        MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    ports:
      - 3000:3000
    container_name: todo-backend-dev-container
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    ports:
      - 27017:27017
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
      image: redis
      command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
      ports:
      - 6379:6379
      volumes: # Declare the volume
          - ./redis_data:/data