version: '3.8'

services:

  app:
    image:
      frontend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    container_name: frontend-container
 